# Generated by Django 5.2.3 on 2025-06-25 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0006_alter_estudiante_nombre_alter_modulo_nombre_costo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matricula',
            name='costo',
        ),
        migrations.DeleteModel(
            name='Costo',
        ),
    ]
