# Generated by Django 5.2.3 on 2025-06-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0008_costo_matricula_costo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
